import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/providers/modal-provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "@/components/ui/toaster"
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { Provider } from "@/components/auth/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <GoogleOAuthProvider clientId="439429871855-3vdr14ne5jp9rrd4inbm1vmhsrvh0kbm.apps.googleusercontent.com">
        <html lang="en">
          <body className={inter.className}>
            <Toaster />
            <ModalProvider />
            <ReactQueryDevtools initialIsOpen={false} />
            {children}
          </body>
        </html>
      </GoogleOAuthProvider>
    </Provider>
  );
}
